/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { precacheAndRoute } from 'workbox-precaching'

declare let self: ServiceWorkerGlobalScope

self.skipWaiting()
clientsClaim()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

self.addEventListener('push', (event) => {
  if (event.data) {
    let payload: any = {}
    try {
      payload = event.data.json()
    } catch (e) {
      payload = { title: 'New Notification', body: event.data.text() }
    }

    const title = payload.title || 'WhisperBox'
    const options = {
      body: payload.body || 'You have a new message.',
      icon: '/pwa-192x192.png',
      badge: '/badge.png',
      data: {
        url: payload.url || '/'
      }
    }

    event.waitUntil(self.registration.showNotification(title, options))
  }
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const urlToOpen = new URL(event.notification.data.url, self.location.origin).href

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window/tab open with the target URL
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i]
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus()
        }
      }
      // If not, open a new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen)
      }
    })
  )
})
