/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core'
import { precacheAndRoute } from 'workbox-precaching'

declare let self: ServiceWorkerGlobalScope

self.skipWaiting()
clientsClaim()

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

self.addEventListener('push', (event) => {
  if (event.data) {
    let payload: any = {}
    try {
      payload = event.data.json()
    } catch (e) {
      payload = { title: 'New Notification', body: event.data.text() }
    }

    const title = payload.title || 'WhisperBox'
    const options = {
      body: payload.body || 'You have a new message.',
      icon: '/pwa-192x192.png',
      badge: '/badge.png',
      data: {
        url: payload.url || '/'
      }
    }

    event.waitUntil(self.registration.showNotification(title, options))
  }
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const targetUrl = new URL(event.notification.data.url || '/', self.location.origin)
  const targetPath = targetUrl.pathname

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Focus an already-open tab whose pathname matches (ignore query/hash).
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i]
        let clientPath = '/'
        try {
          clientPath = new URL(client.url, self.location.origin).pathname
        } catch {}
        if (clientPath === targetPath && 'focus' in client) {
          // Navigate the existing tab to the target URL, then focus it.
          if ('navigate' in client) {
            ;(client as any).navigate(targetUrl.href).catch(() => {})
          }
          return client.focus()
        }
      }
      // No matching tab — open a new one.
      if (self.clients.openWindow) {
        return self.clients.openWindow(targetUrl.href)
      }
    })
  )
})
